name: Run tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  android_tests:
    name: Android tests
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew sample-android:connectedCheck

  ios_tests:
    name: iOS Tests
    runs-on:  macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Select Xcode 11.4
        run: sudo xcode-select -s /Applications/Xcode_11.4.app
      - name: Tests
        run: set -o pipefail && xcodebuild -project sample-ios/SampleiOS.xcodeproj -scheme SampleiOS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.4' test | xcpretty